[package]
name = "testH264"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = { version = "1.1.1", optional = true }
openh264 = "0.2.15"

[dev-dependencies]
env_logger = "0.9"
